on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment?'
        required: true
        type: choice
        options:
          - dev

jobs:
  deploy:
    uses: ./.github/workflows/.terragrunt-template.yml
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      command: apply
