on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment?'
        required: true
        type: choice
        options:
          - dev

jobs:
  deploy-dev:
    if: github.event_name == 'push'
    uses: ./.github/workflows/.terragrunt-template.yml
    secrets: inherit
    with:
      environment: dev
      command: apply

  deploy:
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/.terragrunt-template.yml
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      command: apply
