on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - uses: pnpm/action-setup@v5
        with:
          cache: true
          run_install: |
            - args: [--frozen-lockfile, --prefer-offline]
      - run: pnpm lint
